<!DOCTYPE html>

<html lang="en">

<head>

  <meta charset="UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>WEB-250 | My Course Work</title>

  <link rel="stylesheet" href="css/styles.css">

</head>

<body>

  <header>

    <h1>WEB-250 Assignments</h1>

    <p>Created by: Andrew Jones</p>

  </header>

  <main>

    <?php

    // This line runs on the host and helps confirm PHP is working.

    print '<p>Welcome to the WEB-250 section of my website.</p>';

    ?>

  <nav aria-label="WEB-250 assignments">

  <ul>

    <li>
      <a href="web250/bird-challenge/index.php">Assignment 01</a>
    </li>

    <li>
      <a href="web250/asgn02-inheritance/index.php">Assignment 02</a>
    </li>

    <li>
      <a href="web250/asgn03-static-challenge/index.php">Assignment 03</a>
    </li>

    <li>
      <a href="web250/asgn04-constructors/index.php">Assignment 04</a>
    </li>

    <li>
      <a href="web250/asgn05-bird/index.php">Assignment 05</a>
    </li>

  </ul>

</nav>

  </main>

  <footer>

    <?php
    print '<p>Page generated by PHP on ' . date('F j, Y') . '.</p>';
    ?>

  </footer>

</body>

</html>
